runtime: php55
api_version: 1
default_expiration: 1d

handlers:
- url: /
  script: index.html

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  
- url: /sitemap.xml
  static_files: sitemap.xml
  upload: sitemap.xml

- url: /(.+\.php)
  script: \1

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /fonts/(.*\.eot)
  static_files: fonts
  upload: fonts
  mime_type: application/x-font-otf

- url: /images
  static_dir: images
  
- url: /upload
  static_dir: upload

- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$
  
- url: /upload/.*\.pdf
  mime_type: application/pdf
  static_dir: upload