application: inaveedhome
runtime: php55
api_version: 1

handlers:
- url: /
  script: index.html
#  static_dir: 

- url: /(.*\.php)$
  script: \1

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /fonts/(.*\.eot)
  static_dir: fonts
  mime_type: application/x-font-otf

- url: /fonts/(.*\.svg)
  static_dir: fonts
  mime_type: application/x-font-svg

- url: /fonts/(.*\.ttf)
  static_dir: fonts
  mime_type: application/x-font-ttf

- url: /fonts/(.*\.woff)
  static_dir: fonts
  mime_type: application/x-font-woff

- url: /images
  static_dir: images

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$